services:
  - type: web
    name: bodega-chebitas-directo
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: APP_NAME
        value: Bodega Chebitas
      - key: DATABASE_URL
        value: sqlite:///./bodetronic.db
      - key: SUPPORT_WHATSAPP
        value: 51992657332
      - key: SHEET_SECRET
        value: chebitas-2026
      - key: SHEET_WEBAPP_URL
        value: PEGAR_URL_DE_APPS_SCRIPT
